version: '3'
services:

  app:
    build:
      context: . # docker buildするときのパス、このファイルのあるところからの相対パス
      dockerfile: ./docker/app/Dockerfile # contextのパスから指定
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  mysql-db:
